config/routes.rb
Rails.application.routes.draw do
resources :students
root "students#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	
	before_action :set_student, except:  [:index,:new,:create]

	def index
		@students = Student.all
	end

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)
		if @student.save 
			redirect_to students_path
		else
			render :new
		end
	end

	def edit

	end

	def update
		if @student.update(student_params)
			redirect_to students_path
		else
			render :edit
		end
	end

	def show
	end

	def destroy
		if @student.destroy
			redirect_to students_path
		end
	end

	private

	def student_params
		params.require(:student).permit!
	end

	def set_student
		@student = Student.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Firstbackboneapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br/>
<%= f.label :email %>
<%= f.email_field :email %><br/>
<%= f.label :mobile %>
<%= f.number_field :mobile %><br/>
<%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<header>Edit Student</header>
<%= render "form" %>
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<div id="students"></div>

<script type="text/javascript">
  $(function() {
    // Firstbackboneapp is the app name
    window.router = new Firstbackboneapp.Routers.PostsRouter({students: <%= @students.to_json.html_safe -%>});
    Backbone.history.start();
  });
</script>


<!--
<p id="notice"><%= notice %></p>

<h1>students</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>email</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
        <td><%= student.mobile %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New student', new_student_path %>

app/views/students/new.html.erb
<header>New Student</header>
<%= render "form" %>
<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<h1>Student Details</h1>
<h2><%= @student.name %></h2>
<h2><%= @student.email %></h2>
<h2><%= @student.mobile %></h2>
<%= link_to 'students', students_path %>